### ISSUE TITLE
Package Downgrade

### ISSUE THREAD

**Issue by colespencer1453** [ardalis/Result#106]
Hello! I recognize that this is more of a package management question in general, but I don't have a good enough understanding to know whether this is an out of date issue with this packages specifically. 

I am getting a package downgrade error when trying to build migrations for my project. I was wondering if you'd be able to advise on the best way to handle and resolve this issue.

The error I'm getting is 
```
/tmp/hy3lwwug.fnq/migrationsbundle.csproj : error NU1605: Detected package downgrade: System.Collections from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
/tmp/hy3lwwug.fnq/migrationsbundle.csproj : error NU1605:  migrationsbundle -> Project.Api -> Project.Infrastructure -> Ardalis.Result.AspNetCore 4.1.0 -> Microsoft.AspNetCore.Mvc.Core 2.2.5 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.unix.System.IO.FileSystem 4.3.0 -> System.Collections (>= 4.3.0) 
/tmp/hy3lwwug.fnq/migrationsbundle.csproj : error NU1605:  migrationsbundle -> Project.Api -> Project.Infrastructure -> Ardalis.Result.AspNetCore 4.1.0 -> Microsoft.AspNetCore.Mvc.Core 2.2.5 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.Collections (>= 4.0.11)
```

Which seems to be coming from Ardalis.Result. AspNetCore package. I read Microsofts docs on this error here: https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605 but was still left scratching my head on what the solve was and whether I needed to upgrade or this package does.

Greatly appreciate help if you have the time!

**Comment by ardalis** [comment]
Hmm, I wonder if I can either reference a non-specific version (like 4.*) or if simply updating my package's dependencies to the latest and republishing would do the trick. I'll probably try the latter.
