### ISSUE TITLE
Cannot resolve symbol 'Conflict'

### ISSUE THREAD

**Issue by jerohero** [ardalis/Result#138]
I have been trying to find a way to return 409 Conflict results and discovered that the [git repository](https://github.com/ardalis/Result/blob/main/src/Ardalis.Result/Result.cs) happened to have added this functionality last month. It seems like these changes have yet to be published to Nuget, however, so I would like to know when these changes get published as it is a bit of a pain to work around right now. Thanks!

**Comment by KyleMcMaster** [comment]
@jerohero I'll work with @ardalis to get a new version of the packages out soon.

**Comment by KyleMcMaster** [comment]
@jerohero This should be available now in version 7.1.0.
