### ISSUE TITLE
Do not drop netstandard2.0

### ISSUE THREAD

**Issue by DorianGreen** [ardalis/Result#148]
I noticed that some PRs: #142, #128 made changes to framework versions.
I'd like to add my 2 cents on framework support.

I do agree that Ardalis.Result.AspnetCore should require net8 support once it comes out, but there shouldn't be many issues supporting both net6 and net8, as those are both LTS and not everyone will be able to upgrade right away.

In Adralis.Result and Ardalis.Result.FluentValidation there is no dependency on net6+ at all, and the packages can target netstandard2.0 exclusively. If there are modern language features that are in use then you can add a net6+ target.

There are many projects that are still using .net framework and will take many years to migrate. don't alienate your users by excluding their frameworks, or forcing them to stay on older package versions because they cant update.

As for centralizing versions in Directory.Build.Props, you can provide a default <TargetFrameworks> there, and override it in individual projects. You can also use a naming convention and use a <Choice> element to assign correct versions - anything containing AspnetCore should only have net6+ versions, others should have netstandard2.0

I am happy to create a PR to fix these issues

**Comment by ardalis** [comment]
I'm open to your PR to keep netstandard support. Thanks.
