### ISSUE TITLE
Optional CorrelationId on ErrorList

### ISSUE THREAD

**Issue by philipp985** [ardalis/Result#181]
Would it be acceptable to change
```csharp
public record ErrorList(IEnumerable<string> ErrorMessages, string? CorrelationId);
```
to

```csharp
public record ErrorList(IEnumerable<string> ErrorMessages, string? CorrelationId = null);
```
By this it would be simpler to create an error. At least for my use case the correlationId is not needed and it is marked optional.

```csharp
return Result.Error(new ErrorList(["My error"])
```

As an additional question or wish. I like to old approach to just return one error like this
```csharp
return Result.Error("My error")
```
could this be added back?

**Comment by ardalis** [comment]
Agreed!
