### ISSUE TITLE
Add error messages to Forbidden and UnAuthorized results

### ISSUE THREAD

**Issue by Ahammdan** [ardalis/Result#185]
For certain error states such as Forbidden and UnAuthorized, I found that I require to have some texts in the errors that would help in providing the end user with the reason of the error state. This behavior is similar to what was implemented with the conflict and NotFound error result.  

I am willing to work on a PR for this if it's acceptable.

**Comment by ardalis** [comment]
Sure, that makes sense, as long as they're optional. Go for it, thanks.

**Comment by ardalis** [comment]
Fixed by #190
