### ISSUE TITLE
.ToMinimalApiResult not supported on NET6

### ISSUE THREAD

**Issue by sburbano** [ardalis/Result#203]
Hi,

Is there any reason for not supporting the MinimalAPI extensions on NET6? 

They are `#ifdef`ed-out, but I tried a local compilation after removing the `#ifdef`and it compiled just fine (if it compiles, it works, right? :laughing:).

https://github.com/ardalis/Result/blob/bb930b30fe6439113ef0fe21390d1f6548efe492/src/Ardalis.Result.AspNetCore/MinimalApiResultExtensions.cs#L8

My guess is that they were inadvertently left out when adding support for NET7 :fearful: 

https://github.com/ardalis/Result/commit/8432b42ddc820112747a9af1331391fbd9085dbb#diff-5e6302b9ee60d6b65eadf82e51d75b7d842967324d86bbfb5c51f745b51743ab

If that's correct, please, reintroduce support.

**Comment by ardalis** [comment]
This should be in the next release.

**Comment by ardalis** [comment]
Added in v10
https://github.com/ardalis/Result/releases/tag/v10.0.0
