### ISSUE TITLE
Add Bind in addition to Map to support Railway Oriented Programming

### ISSUE THREAD

**Issue by christophercalm** [ardalis/Result#211]
I have found the map method to be extremely useful when chaining result types. In addition to the Map method, I have added Bind method with async overloads that allow me to combine operations that may fail or be invalid. Here is an example of a flow that is enabled by these extensions. 

```csharp
Result addOrUpdateResult = await GetProfile(request.Id, ct)
    .BindAsync(profile => AddOrUpdateExperience(profile, request))
    .BindAsync(updatedProfile => SendIntegrationEvent(updatedProfile, request, ct))
    .BindAsync(_ => PersistChanges(request))
    .ToAsyncResult();

return addOrUpdateResult;
```

This adds support for railway oriented programming [Railway Oriented Programming](https://fsharpforfunandprofit.com/rop/) that makes for very clean and terse mediatr handlers that create an easy to read data pipeline. I have used this in conjuction with your modular monolith course and found a lot of value in it. 

Currently my version only supports the states that I use (Invalid, Error, and Success), but it would be trivial to add the rest. Would you be interested in a PR adding this to the library?

**Comment by KyleMcMaster** [comment]
With the introduction of `Map` in #97, this library does have some support for functional programming practices and as a fan of Railway Oriented Programming I would be in favor of adding a `BindAsync` method too. I have had a good experience using similar approaches from `CSharpFunctionalExtensions`.
