### ISSUE TITLE
Update README to show typical use cases

### ISSUE THREAD

**Issue by ardalis** [ardalis/Result#36]
The sample has several ways to use the library, but these should be called out in the README file as well. Should be broken up into just using the Result object and its helpers, and then separately the integration with AspNetCore for Actions/Endpoints.

**Comment by emmysteven** [comment]
I'm currently working a project that uses the clean architecture a.k.a onion architecture.
I'll install this package come up with a use case for **integration with AspNetCore for Actions/Endpoints**

**Comment by ardalis** [comment]
This is done.
