### ISSUE TITLE
Pagination option

### ISSUE THREAD

**Issue by HamedFathi** [ardalis/Result#47]
I am not sure but, what if we have a paged info property in `Result` class?

```cs
public class Result
{
    // ...
    public PagedInfo<T> PagedInfo { get; set; } = null;
    // ...
}

public class PagedInfo<T>
{
    public long PageNumber { get; set; }
    public long PageSize { get; set; }
    public long TotalPages { get; set; }
    public long TotalRecords { get; set; }
}
```

I think it covers paging scenarios too.

**Comment by ardalis** [comment]
Could be useful. I'm not sure you'd always want it, though, so maybe an alternate `PagedResult` base type?

**Comment by HamedFathi** [comment]
> so maybe an alternate PagedResult base type

Looks good, Should it be part of your library or just a simple inheritance on the user side?

**Comment by ardalis** [comment]
I'd consider a PR with it, if you included some tests and sample usage. You open to that?

**Comment by HamedFathi** [comment]
@ardalis 

Probably, Give me some time to try it.

**Comment by ardalis** [comment]
How's it coming?

**Comment by HamedFathi** [comment]
Sorry, I was sick for a while. I do it in my free time.

**Comment by ShadyNagy** [comment]
@ardalis & @HamedFathi  
Is that we are looking for PR #52
