### ISSUE TITLE
FluentValidation dependency conflict

### ISSUE THREAD

**Issue by csteele86** [ardalis/Result#61]
The FluentValidation dependency in the [Ardalis.Result.FluentValidation.csproj](https://github.com/ardalis/Result/blob/master/src/Ardalis.Result.FluentValidation/Ardalis.Result.FluentValidation.csproj) specifies that you must have version >= 9.x, but with version 10.x, there was a breaking change that prevents this from working: https://docs.fluentvalidation.net/en/latest/upgrading-to-10.html#validationresult-errors-type-change. Here is where the code will break if you try using version 10.x of FluentValidation with Ardalis.Result: https://github.com/ardalis/Result/blob/34087084dab76d1d063a4d80497294f612f2bff6/src/Ardalis.Result.FluentValidation/FluentValidationResultExtensions.cs#L14
Here is the exception:
```
Message: 
    Test method <redacted test name> threw exception: 
    System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<FluentValidation.Results.ValidationFailure> FluentValidation.Results.ValidationResult.get_Errors()'.
  Stack Trace: 
    FluentValidationResultExtensions.AsErrors(ValidationResult valResult)
```

**Comment by ardalis** [comment]
Thanks! I'll try and release an update soon.

**Comment by csteele86** [comment]
@ardalis, how would you want this fixed? I see it being fixed a few different ways.

**Comment by ardalis** [comment]
I haven't investigated it yet but my default approach would be to make it work with vLatest of [dependency] and go from there. If there's some reason it *can't* work on the latest, I'd have to reassess.

**Comment by csteele86** [comment]
@ardalis, with that in mind here are my thoughts on how to fix this properly:
* 2 PRs:
  * Update the FluentValidation dependency to the max of 9.x
    * This is necessary to fix the bug and keep things backwards compatible.
    * Ardalis.FluentValidation will now be 3.0.2 instead of 3.0.1
  * Update the FluentValidation dependency to the minimum of 10.x
    * Ardalis.FluentValidation will now be 4.0.0 because of the FluentValidation dependency being increased by a major version and 9.x is not usable with 10.x

How does this sound? Other suggestions? I can commit to fixing this too.
