### ISSUE TITLE
Release 3.3.1 doesn't have latest ResultStatus - missing Unauthorised

### ISSUE THREAD

**Issue by khandelwal-arpit** [ardalis/Result#72]
The release v3.3.1 has the following definition of ResultStatus:

```
namespace Ardalis.Result
{
    public enum ResultStatus
    {
        Ok,
        Error,
        Forbidden,
        Invalid,
        NotFound
    }
}

```
Whereas the source code has an additional entry of **Unauthorized** which is needed for handling incorrect password kind of cases. Can you please update the release so that it has the correct Enum?

**Comment by ardalis** [comment]
This was published today as version 3.1.2.

https://www.nuget.org/packages/Ardalis.Result/3.1.2
