### ISSUE TITLE
Latest Ardalis.Result.AspNetCore not published?

### ISSUE THREAD

**Issue by molinch** [ardalis/Result#78]
Thanks for the lib it's really great.
There are many change that are in github but not published to nuget, could latest Ardalis.Result.AspNetCore be pushed?

See, the one in nuget is very old:
![image](https://user-images.githubusercontent.com/5130190/146779799-a14a9ff9-ffe8-4674-a157-ba415db8d8dd.png)

**Comment by ardalis** [comment]
Yeah it has been a bit... I'll try and get an update out in January.

**Comment by ardalis** [comment]
Published!
