### ISSUE TITLE
Adding additional Result types for additional scenarios

### ISSUE THREAD

**Issue by nhwilly** [ardalis/Result#84]
I've started using `Result<T>` in a lot more places than I originally thought, and I've found some cases where I believe a few more options would be helpful.

As an example, I want to return the following:

- An `ResultStatus.Unchanged` carrying no value in the event nothing is modified
- A `ResultStatus.Conflict` perhaps with a payload of what EF Core has available for database values, current values, etc.
- A `ResultStatus.AlreadyExists` with no payload
- A `ResultStatus.DetailedError` with coded results instead of strings.
- A `ResultStatus.Success` with no payload

What I've been using it for is to trap the exceptions in the repository and return only Result(s) which I handle in the endpoint.

I don't know, this might be a terrible idea, but this is a tiny bit like a discriminated union where I'm getting varied results from the same call.  I did this in Dart and it was pretty handy.

If there is no interest, or someone's already working on it, I'll drop it.  Perhaps clone the repo and just keep the project separate.

I've never contributed to open source projects before, so this is new to me, but if other people find it useful, I'm happy to contribute something.

Please advise.  Thanks.

**Comment by ardalis** [comment]
I'm open to additional options here. Feel free to make a PR. Ping me if you need any assistance.

**Comment by nhwilly** [comment]
Recent updates solve the issues I was having.
