### ISSUE TITLE
Support FluentValidation's ErrorCode property of ValidationResult in ValidationError

### ISSUE THREAD

**Issue by fil-at-werma** [ardalis/Result#87]
Unfortunately, our team decided to ditch Ardalis Result because of this very lacking feature.
If you want, I can post a PR, it should really be only 2 lines of code. (Maybe + testing)

**Comment by fil-at-werma** [comment]
Ok, I'll do it, then. Please mind: this will be my _very first_ GitHub / Open Source PR and contribution.

**Comment by ardalis** [comment]
Awesome! Welcome to being an open source contributor :)
