### ISSUE TITLE
NotFound override to return a body

### ISSUE THREAD

**Issue by berv63** [ardalis/Result#95]
We'd like to use the `result.NotFound()` but designate the difference between 404 (route doesnt exist) and 404 (resource doesnt exist) by returning an error in the body.

**Comment by berv63** [comment]
I already have a new branch locally with these changes and would be happy to submit a PR. But I'm getting access deinied.

**Comment by ardalis** [comment]
You probably need to fork this repo, so your repo recognizes it as a related remote? I'm definitely open to the PR.

**Comment by berv63** [comment]
Yep I got someone familiar with the pattern to help me get a PR in. See above ^. Thanks!
