### ISSUE TITLE
[Question] What would be a good way to return CreatedAtAction 201 result?

### ISSUE THREAD

**Issue by philipp985** [ardalis/Result#99]
Hello,
thank you for the good library and good ideas from concepts!

What would be an elegant / good way to solve this problem. I could not find anything in the calculation.

```
[HttpPost]
[ProducesResponseType(StatusCodes.Status201Created)]
public async Task<ActionResult<InventoryInspectionDoneDTO>> Create([FromBody] InventoryInspectionDoneCreateDTO dto)
{
       var resp = (await _inventoryInspectionsDoneService.CreateAsync(dto)).Map(x => 
       _mapper.Map<InventoryInspectionDoneDTO>(x));
       if (resp.IsSuccess)
          {
              return CreatedAtAction(nameof(GetById), new { id = resp.Value.Id }, resp.Value);
          }

   return this.ToActionResult(resp);
}
```

One idea would be write a custom extension but maybe there is chance to include it in this library.

Thanks for any ideas!

**Comment by ardalis** [comment]
I think some of what is in this PR could be applied: https://github.com/ardalis/Result/pull/92.

**Comment by ardalis** [comment]
We now have a Created result.
